### PR TITLE
Pascal case for constant MaximumBatchSize

### PR DESCRIPTION
**Pull request by johnbindel**

### CODE REVIEW

**Comment by vturecek** [comment]
@johnbindel Thanks for that! 
Assigning to @dkkapur

**Comment by dkkapur** [comment]
Thank you @johnbindel! Just merged the PR; appreciate your working through the details and updating this. I look forward to any other changes you have in the future!

**Comment by johnbindel** [comment]
Glad to help out. Two questions:
1- What's the best way to help contribute to Service Fabric? What enhancements are people asking for in the open sourced code for services and samples?
2- When will we see more of the core Service Fabric code make it to github?

**Comment by dkkapur** [comment]
1. Encourage you to have a look [here](https://github.com/Azure/service-fabric). People often provide suggestions and feedback for changes [in this repo](https://github.com/Azure/service-fabric-issues ) and [in this forum](https://feedback.azure.com/forums/293901-service-fabric). 
2. We're working on this and its a priority for us, hopefully more of it will become open-sourced over time.

**Pull request merged**
